### ISSUE TITLE
Bit of a me problem, but am unsure how to use this as it is not EXE

### ISSUE THREAD

**Issue by RisingArmechadon** [filler56789/ffdcaenc-2#2]
I don't know anything about c programming and am unsure of how to add this to audiomuxer as it is not an exe. Can someone compile it for me, or show me the way to compile it?

**Comment by filler56789** [comment]
32-bit .exe: https://forum.videohelp.com/threads/348702-ffdcaenc-(an-upgrade-to-dcaenc)#post2337613

64-bit .exe: https://forum.videohelp.com/threads/399044-Looking-for-64bit-versions-of-a-few-command-line-tools#post2597048
